name 'jdowning/influxdb'
version '0.2.0'
source 'https://github.com/justindowning/puppet-influxdb'
author 'Justin Downing'
license 'Apache License, Version 2.0'
summary 'Setup and manage influxdb'
description 'Setup and manage influxdb'
project_page 'https://github.com/justindowning/puppet-influxdb'

dependency 'nanliu/staging', '>= 0.4.0'
dependency 'puppetlabs/inifile', '>= 1.0.0'
